
name: Server CI workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
      runs-on: self-hosted
  
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Build with Maven
          run: mvn --batch-mode --update-snapshots package
        - name: Extract Version from pom.xml
          id: extract-version
          run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
  deploy:
    runs-on: self-hosted
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          build-args: "VERSION=${{ steps.extract-version.outputs.version }}"
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: '${{ secrets.REGISTRY_URL }}/organizer-bot:${{ steps.extract-version.outputs.version }}'
