
name: Server CI workflow

on:
  push:
    branches: [ organizer_2.0 ]
  pull_request:
    branches: [ organizer_2.0 ]
jobs:
  build:
      runs-on: self-hosted
  
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '20'
            distribution: 'temurin'
        - name: Build with Maven
          run: mvn --batch-mode --update-snapshots package
        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v3
          with:
            name: jar
            path: ./target/organizer2-*.jar
            retention-days: 1
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - 
      #   name: Login to private registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ secrets.REGISTRY_URL }}
      #     username: ""
      #     password: ""
      - name: Get version
        id: version
        shell: powershell
        run: |
          $version = (Get-Content -Path "pom.xml" | Select-String -Pattern "<version>(.*?)</version>").Matches.Groups[1].Value;
          echo "RELEASE_VERSION=$version" >> $env:GITHUB_OUTPUT
      - name: Write key files
        run: |
          [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String('${{ secrets.AUTH }}')) | Out-File -Encoding "utf8" ./credentials.properties
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          path: ./target/
          name: jar
      - name: Print
        run: |
          Get-ChildItem
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          build-args: "VERSION=${{ steps.version.outputs.RELEASE_VERSION }}"
          platforms: linux/arm64
          # builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: '${{ secrets.REGISTRY_URL }}/organizer-bot:${{ steps.version.outputs.RELEASE_VERSION }}'
